### ISSUE TITLE
Update to R 4.X

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/genomics-workshop#114]
@ytakemon recently noted that the AMI has an old version of R installed. Leaving this issue here to remind myself to update to 4.X. Also need to check in with the R Genomics Maintainers to make sure that's not going to break code in the current lesson.

**Comment by kerchner** [comment]
I'm not entirely sure, but I think upgrading to R 4.2 and beyond is difficult while still on Ubuntu 16 - hence #133

**Comment by naupaka** [comment]
I think the code used in the current R-genomics lessons should be fine with R 4.2+ since that is what most of us are using to do the development anyway. And since those lessons are still beta I think any fixes we would need to make could be made now with less hassle than later on down the road.

**Comment by kerchner** [comment]
We have an AMI that we used recently (August 2022) that we would like to contribute.  It updated both the version of Ubuntu (I think to 20? I need to double check) as well as the version of R to 4.2.1 and RStudio server.  Hoping to tidy that up and push a pull request here with a change to the AMI id and other associated changes, which may include key screenshots etc.   Let me know if that sounds like it would be useful.

**Comment by naupaka** [comment]
Speaking for myself I think that would be great.

**Comment by kerchner** [comment]
Awesome, we (myself, @cgaylord-gwu, and @aklwong) will plan to move this forward.

**Comment by naupaka** [comment]
I think at the moment the Carpentries admin folks have to spin up AWS instances for the workshops manually, so they should be in the loop on any changes. cc @ErinBecker

**Comment by kerchner** [comment]
That would also drive the choice of pull request reviewers for this one

**Comment by tobyhodges** [comment]
Thanks @kerchner this sounds like it would be really helpful. If you can provide an AMI, the Core Team will be happy to try to use it to spin up an AWS instance. We could then share that with @naupaka and/or any of the other R Genomics Maintainers who are interested in helping out, so that they can test out the code examples in the lesson?

**Comment by kerchner** [comment]
Great idea @tobyhodges, we hope to have an AMI to share with you very soon.

**Comment by kerchner** [comment]
@tobyhodges @naupaka  I've created an AMI that I think is ready for the Core Team to test.   The AMI id is `ami-04dd77cd58b3ec654` (in the `N. Virginia` region) and it's entitled `Data Carpentry Genomics with R 4.2`

The AMI includes the following updates:
- Operating system has been upgraded from Ubuntu 16 to Ubuntu 20.04.5 LTS
- R has been upgraded from 4.0 to `4.2.2 Patched (2022-11-10 r83330)`
- RStudio has been upgraded to `2022.12.0 Build 353`
- `fastqc` has been upgraded from 0.11.7 to 0.11.9
- `trimmomatic` has been upgraded from 0.37 to 0.39
- `bwa`, `samtools` were already on the latest versions
- `bcftools` has been upgraded from 1.8 to 1.9

The newer versions of the command-line tools should be equally available for Mac/Windows users as they are for Linux, since they're all installed via conda.

Once the Core Team has had a chance to test, then I would be glad to create a pull request with updated screenshots and command-line output as needed, and/or we can collaborate on a branch.

**Comment by naupaka** [comment]
Thanks! Tagging @JasonJWilliamsNY @ytakemon @poterlowicz-lab (the other R-genomics maintainers) so they're in the loop on this as well.

**Comment by kerchner** [comment]
Thanks @crazyhottommy!   I'll start putting together a branch/PR with any needed updates to the lesson pages, so that they match what learners will see when using the new AMI.

**Comment by ErinBecker** [comment]
@kerchner and @datacarpentry/curriculum-advisors-genomics - I cannot tell you how excited I am to see this group moving forward independently to update the AMI. Absolutely amazing work team! Thank you!!

**Comment by twrightsman** [comment]
This seems solved due to the merge of https://github.com/datacarpentry/genomics-workshop/pull/136.
