### ISSUE TITLE
Suggestion: Add a lesson on connecting your Rstudio with your GitHub account

### ISSUE THREAD

**Issue by Eugeniia** [datacarpentry/genomics-workshop#126]
It's a suggestion. For those who want to dive deeper, it would be nice to teach how to connect your Rstudio with GitHub. Once you created your first Rstudio project, created and organized your files, you can commit the changes and push your project to GitHub.

**Comment by shukwong** [comment]
Hi @Eugeniia, I think this is a great suggestion and indeed a very useful skill to have. What do you think @ACharbonneau and @anwarMZ ?

**Comment by ckisielinski** [comment]
Hi there! I very much agree with creating a lesson or other resource on this subject. I was recently a helper for a different workshop that utilized both Rstudio and GitHub, and we ran into several technical hiccups when trying to connect both services on the fly. Perhaps this is something that can also be included during pre-workshop download parties?

**Comment by crazyhottommy** [comment]
Hi all, 

this is Tommy and I am serving as the chair of the genomic curriculum advisor committee. The Committee met and we gave our votes for this:

@aschuerch : a useful skill but further grows the curriculum. requires people to know Git to find it useful.
@JasonJWilliamsNY in the R lesson there is a tip, mentioning version control and good practices, and that these can be incorporated, but not trying to teach it.
@crazyhottommy  then it sounds like the CAC is ready to recommend against including this.
@JasonJWilliamsNY: when replying, you could mention that the tip exists in the R lesson. (https://datacarpentry.org/genomics-r-intro/01-introduction/index.html#tip-make-your-project-more-reproducible-with-renv) perhaps they could add a sentence or two if needed. 

Most of us think this isn't a good idea because we don't discuss git anywhere else in the lessons, probably best just to add a box linking to the actual git lesson that has this information

Thanks,  all the maintainers for your hard work and we appreciate your feedback and suggestions.

Best,
Tommy

**Comment by twrightsman** [comment]
Thank you again to the original contributors for the suggestion! Given the advisement by the Genomics CAC I will consider this issue as closed.
