### ISSUE TITLE
Truncated files in sample data

### ISSUE THREAD

**Issue by k8hertweck** [datacarpentry/genomics-workshop#25]
In the cloud instance, both data files in `dc_sample_data/untrimmed_fastq` end with nucleotide lines, rather than quality scores.

**Comment by ErinBecker** [comment]
@tracykteal can you advise on this? Were these files truncated on purpose in order to reduce file size? If so, then we can just remove the lines for the incomplete records at the end of each file. If this was done in order to show a point about checking data quality, then that can be made an explicit exercise.

**Comment by tracykteal** [comment]
They were truncated to reduce file size. So, we can fix this. We'll need to create a new instance though with the correct files. This isn't a big deal, but maybe we should identify all the things we want to update on the current instance. Should we have a 'update the instance' in the 'genomics-workshop' repo?

**Comment by ErinBecker** [comment]
This has been fixed in the new instance. We'll be putting in a PR with the new instance number shortly! Closing here.
