### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/genomics-workshop#7]
- spreadsheet program
- something that lets them ssh
- R and RStudio

**Comment by ErinBecker** [comment]
Current [installation instructions](http://www.datacarpentry.org/genomics-workshop/setup/) do not include a spreadsheet program or R and RStudio. Installation instructions need to be updated to include all necessary software. We should also split the install instructions so that the necessary software for each version of the workshop is shown separately.

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/genomics-workshop/pull/32
